// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: partner/service/v1/global_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalErrorReason int32

const (
	GlobalErrorReason_PERMISSION_DENY GlobalErrorReason = 0
)

// Enum value maps for GlobalErrorReason.
var (
	GlobalErrorReason_name = map[int32]string{
		0: "PERMISSION_DENY",
	}
	GlobalErrorReason_value = map[string]int32{
		"PERMISSION_DENY": 0,
	}
)

func (x GlobalErrorReason) Enum() *GlobalErrorReason {
	p := new(GlobalErrorReason)
	*p = x
	return p
}

func (x GlobalErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_partner_service_v1_global_error_proto_enumTypes[0].Descriptor()
}

func (GlobalErrorReason) Type() protoreflect.EnumType {
	return &file_partner_service_v1_global_error_proto_enumTypes[0]
}

func (x GlobalErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalErrorReason.Descriptor instead.
func (GlobalErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_partner_service_v1_global_error_proto_rawDescGZIP(), []int{0}
}

var File_partner_service_v1_global_error_proto protoreflect.FileDescriptor

var file_partner_service_v1_global_error_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x2e, 0x0a,
	0x11, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e,
	0x5f, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x00, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x1e, 0x5a,
	0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x62, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_partner_service_v1_global_error_proto_rawDescOnce sync.Once
	file_partner_service_v1_global_error_proto_rawDescData = file_partner_service_v1_global_error_proto_rawDesc
)

func file_partner_service_v1_global_error_proto_rawDescGZIP() []byte {
	file_partner_service_v1_global_error_proto_rawDescOnce.Do(func() {
		file_partner_service_v1_global_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_partner_service_v1_global_error_proto_rawDescData)
	})
	return file_partner_service_v1_global_error_proto_rawDescData
}

var file_partner_service_v1_global_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_partner_service_v1_global_error_proto_goTypes = []interface{}{
	(GlobalErrorReason)(0), // 0: global_error.v1.GlobalErrorReason
}
var file_partner_service_v1_global_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_partner_service_v1_global_error_proto_init() }
func file_partner_service_v1_global_error_proto_init() {
	if File_partner_service_v1_global_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_partner_service_v1_global_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partner_service_v1_global_error_proto_goTypes,
		DependencyIndexes: file_partner_service_v1_global_error_proto_depIdxs,
		EnumInfos:         file_partner_service_v1_global_error_proto_enumTypes,
	}.Build()
	File_partner_service_v1_global_error_proto = out.File
	file_partner_service_v1_global_error_proto_rawDesc = nil
	file_partner_service_v1_global_error_proto_goTypes = nil
	file_partner_service_v1_global_error_proto_depIdxs = nil
}
