server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9090
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/partner_matching?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1
    read_timeout: 0.2s
    write_timeout: 0.2s
    port: :6379
    lock_key: "recommend_lock_key"
constant:
  userLoginState: userLoginState
  sessionTimeout: 86400
  defaultRole: 0
  adminRole: 1
